[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
gas_reports = ["*"]
remappings=[
    "@openzeppelin=lib/openzeppelin-contracts/"
]

[rpc_endpoints]
viction_mainnet = "https://rpc.viction.xyz"
viction_local = "http://localhost:8545/"

[etherscan]
viction_mainnet = { key="", url = "https://vicscan.xyz/api/" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options